#index:
#    path: /
#    controller: App\Controller\DefaultController::index
calendar:
  path: /calendar
  controller: App\Controller\CalendarController::index
# app_consultation_calendar:
#   path: /json
#   controller: App\Controller\ConsultationController::consultationsJson
# search:
#   path: /search1
#   controller: App\Controller\SearchController::search